global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8888']

  # When deploying on AWS, you'd add EC2 instance monitoring here
  - job_name: 'node-exporter'
    ec2_sd_configs:
      - region: us-east-1  # Replace with your AWS region
        port: 9100
        filters:
          - name: tag:Project
            values: [ProductSearchAPI]
